### PR TITLE
Get container id from mountinfo when cgroup is empty

### LINKED ISSUE #1647: Gladys doesn't keep the MQTT Brocker URL after docker restart when using docker-compose
**Describe the bug**
When running Docker Gladys with docker compose every time the container is restarted the MQTT configuration doesn't load (although is still saved in the database).

**To Reproduce**

1. With a docker compose file like this:
```yml
# docker-compose.yml
version: "3.3"
services:
  gladys:
    restart: always
    privileged: true 
    network_mode: host
    container_name: gladys
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8090
      - TZ=Europe/Madrid
      - SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCAL_DATA_DIR}/gladys:/var/lib/gladysassistant"
      - "/dev:/dev"
      - "/run/udev:/run/udev:ro"
    image: "gladysassistant/gladys:v4"
  mosquitto:
    restart: always
    container_name: mosquitto
    image: eclipse-mosquitto:2
    volumes:
      - ${LOCAL_DATA_DIR}/mosquitto/config/:/mosquitto/config/
      - ${LOCAL_DATA_DIR}/mosquitto/log/:/mosquitto/log/
      - ${LOCAL_DATA_DIR}/mosquitto/data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
```
3. Go to `<gladys-server-domain>/dashboard/integration/device/mqtt/setup`
4. Setup the Broker URL to `mqtt://localhost`
5. Everything should work fine
6. Restart the Gladys container
7. Go to `<gladys-server-domain>/dashboard/integration/device/mqtt/setup`
8. The Broker URL is lost

**Expected behavior**
It should keep loading the Broker URL after restart.

**Your Gladys installation (please complete the following information):**
- Raspberry Pi 4 
- Debian GNU/Linux 11 (bullseye)
- Docker version 20.10.20, build 9fdeb9c

**Additional context**
When restarting the Docker container this logs are shown:
```
<warn> service.start.js:44 (Service.start) Unable to start service zigbee2mqtt PlatformNotCompatible [Error]: DOCKER_CGROUP_CONTAINER_ID_NOT_AVAILABLE
    at System.getGladysContainerId (/src/server/lib/system/system.getGladysContainerId.js:45:13)
    at System.getNetworkMode (/src/server/lib/system/system.getNetworkMode.js:16:25)
    at Zigbee2mqttManager.init (/src/server/services/zigbee2mqtt/lib/init.js:18:23)
    at Object.start (/src/server/services/zigbee2mqtt/index.js:17:5)
    at Service.start (/src/server/lib/service/service.start.js:33:7)
```

After some research I found [this Stackoverflow entry](https://stackoverflow.com/questions/68816329/how-to-get-docker-container-id-from-within-the-container-with-cgroup-v2) which lead me to verify that `/proc/self/cgroup` is actually empty.
The issue can be solved when running docker using the `--cid` or `--cgroupns` flag, but none of those options is available in docker compose.

### PR DESCRIPTION
**Pull request by magarcia**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

This PR fixes #1647, when `/proc/self/cgroup` doesn't contain the container ID it tries to get it from `/proc/self/mountinfo`.

### CODE REVIEW

File: server/lib/system/system.getGladysContainerId.js [hunk 1]
```diff
@@ -42,7 +42,15 @@ async function getGladysContainerId() {
       // then, we remove .scope
       [containerId] = firstPart.split('.scope');
     } else {
-      throw new PlatformNotCompatible('DOCKER_CGROUP_CONTAINER_ID_NOT_AVAILABLE');
+      const mountinfo = await fs.promises.readFile('/proc/self/mountinfo', 'utf-8');
```
Comment (Pierre-Gilles) [inline server/lib/system/system.getGladysContainerId.js]: What happens if this file doesn't exist? should be properly catched :)

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Thanks for this PR! 🙏

Have you tried this PR in real life with docker-compose? (You can build a Gladys docker image very easily directly from Github, I can explain how if needed)

**Comment by magarcia** [comment]
> Thanks for this PR! 🙏
> 
> Have you tried this PR in real life with docker-compose? (You can build a Gladys docker image very easily directly from Github, I can explain how if needed)

I didn't try on docker-compose yet. If you can explain how to build the docker image directly from GitHub it would be nice, I have some trouble setting up the project on the Apple Silicon (I'm using GitHub Codespaces to develop 😅)

File: server/lib/system/system.getGladysContainerId.js (hunk 1 above)
Comment (magarcia) [reply server/lib/system/system.getGladysContainerId.js]: Done!! 😄 

I took the liberty to refactor the method a little bit and split it into 3 functions: `getContainerIdFromCidfile`, `getContainerIdFromCgroup` and `getContainerIdFromMountinfo`. So if it's not found in one file, goes to the next one until it's found or throws an Error.

**Comment by Pierre-Gilles** [comment]
@magarcia 

> If you can explain how to build the docker image directly from GitHub it would be nice

It's very easy! In your fork, create 3 environnement variable for Github Actions pointing to a DockerHub account (to push the image to): 

```
DOCKERHUB_PASSWORD (can be an API KEY password)
DOCKERHUB_REPO (the docker image to push too, example: `magarcia/gladys-test` )
DOCKERHUB_USER (your username on DockerHub)
``` 

Then, go to: 

Screenshot 2022-11-14 at 15 00 31

Choose the arch you want to build (you can build all, but it takes 1 hour 20 minutes, if you want to try on amd64 cpu only, can be a 2 minutes build )

Screenshot 2022-11-14 at 15 00 43


> I have some trouble setting up the project on the Apple Silicon

Weird, I'm on Apple Silicon too (M1 Pro) and it works fine! 

If you want we can talk about it on the forum, are you on the forum? (our international forum: https://en-community.gladysassistant.com/, we also have a french forum but it seems you're from spain! :) )

**Comment by VonOx** [comment]
Hi @magarcia , tested your PR with no regression, good job.

To build with Github Actions you need to define Repository secrets:

* DOCKERHUB_USER ( obiously your Dockerhub username )
* DOCKERHUB_PASSWORD 
* DOCKERHUB_REPO ( It's the repository in dockerhub , magarcia/gladys for exemple )

After that, you can use github actions on your fork.

image

**Comment by VonOx** [comment]
@Pierre-Gilles Tested on my side, no regression

I'm waiting for image to test with compose.

File: server/lib/system/system.getGladysContainerId.js (hunk 1 above)
Comment (Pierre-Gilles) [reply server/lib/system/system.getGladysContainerId.js]: Looks way better now :) Thanks for the refacto, much cleaner now!

**Comment by magarcia** [comment]
@Pierre-Gilles @VonOx tested with compose and works without issue. 😄

**Review by VonOx — APPROVED** [review]
@Pierre-Gilles docker & docker-compose ok
Thanks @magarcia

**Review by Pierre-Gilles — APPROVED** [review]
Looks good to me! Thanks for this PR and for your work 🙏

**Comment by Pierre-Gilles** [comment]
@magarcia Did you manage to install Gladys on M1 chip ? I can help if needed :)

**Comment by Pierre-Gilles** [comment]
@all-contributors please add @magarcia for code

**Comment by Pierre-Gilles** [comment]
@magarcia Fix is live in latest version of Gladys! 

https://github.com/GladysAssistant/Gladys/releases/tag/v4.12.2
