### PR TITLE
fix(front): Fix integrations search

### LINKED ISSUE #1740: Search on integration page doesn't seem to be working on mobile
https://community.gladysassistant.com/t/gladys-assistant-4-20-redesign-du-site-gladys-assistant/8080/31?u=pierre-gilles

### PR DESCRIPTION
**Pull request by cicoub13**
If User inputs a word with capital letter (by default on mobile), comparison with integrations names should take it in account and lowercase full input search

Fixes #1740

### CODE REVIEW

File: front/src/actions/integration.js [hunk 1]
```diff
@@ -43,7 +43,10 @@ const actions = store => ({
     if (searchKeyword && searchKeyword.length > 0) {
       selectedIntegrations = selectedIntegrations.filter(integration => {
         const { name, description } = integration;
-        return name.toLowerCase().includes(searchKeyword) || description.toLowerCase().includes(searchKeyword);
+        return (
+          name.toLowerCase().includes(searchKeyword.toLowerCase()) ||
```
Comment (atrovato) [inline front/src/actions/integration.js]: Can you please set `searchKeyword.toLowerCase()` in a common variable (defined between line 43 and 44), to avoid to compute "same" lowercase in the loop.

**Review by atrovato — CHANGES_REQUESTED** [review]
Nice, thanks for finding this!
I add a little "optimization" comment.

File: front/src/actions/integration.js (hunk 1 above)
Comment (cicoub13) [reply front/src/actions/integration.js]: Done (push forced)

**Review by atrovato — APPROVED** [review]

**Review by Pierre-Gilles — APPROVED** [review]
Thanks for finding this, and thanks @atrovato for the review 🙏
