### PR TITLE
fix(conversation): Spread chat messages to same user open tabs

### LINKED ISSUE #553: Spread own chat messages to other opened window of the same user (websocket)

### PR DESCRIPTION
**Pull request by cicoub13**
Fix #553

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [X] Are tests passing? (`npm test` on both front/server)
- [X] Is the linter passing? (`npm run eslint` on both front/server)
- [X] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [x] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Synchronize discussion messages between tabs

To test, open two discussion tabs in your browser (or on two different machines) and send a message. Full conversation must be synchronized between all tabs.

A question about where I put the websocket send in the server (in the controller). Is it the good place ?
https://github.com/GladysAssistant/Gladys/pull/1051/files#diff-53be8e5edecb97124c3eb6ea3c770a16db9acaf8563fa01c24b09cfc4eefae85R32

### CODE REVIEW

**Comment by cicoub13** [comment]
https://user-images.githubusercontent.com/1773153/105813586-5b905300-5fb0-11eb-98df-8d65d1f46b93.mov

File: front/src/actions/message.js [hunk 1]
```diff
@@ -74,11 +78,12 @@ function createActions(store) {
       });
       const messageText = state.currentMessageTextInput;
       try {
+        const tempId = uuid.v4();
         const newMessage = {
           text: messageText,
-          created_at: new Date()
+          created_at: new Date(),
+          uuid: tempId
```
Comment (Pierre-Gilles) [inline front/src/actions/message.js]: Why did you use a "uuid" attribute and not "id" like at most places?

File: server/api/controllers/message.controller.js [hunk 2]
```diff
@@ -25,8 +25,15 @@ module.exports = function MessageController(gladys) {
       source_user_id: req.user.id,
       user: req.user,
       created_at: req.body.created_at || new Date(),
+      uuid: req.body.uuid,
```
Comment (Pierre-Gilles) [inline server/api/controllers/message.controller.js]: Be careful, this will be sent to the `message.create` function, that isn't supposed to accept a `uuid` attribute.

If you really need this id, you could generate the id here and use it when inserting the message in DB then, so ID are consistent.

File: front/src/actions/message.js [hunk 3]
```diff
@@ -43,13 +43,17 @@ function createActions(store) {
       });
     },
     pushMessage(state, message) {
+      let newMessages = store.getState().messages;
+      if (message.uuid && message.uuid === newMessages[newMessages.length - 1].uuid) {
```
Comment (Pierre-Gilles) [inline front/src/actions/message.js]: This won't necessarily work, because if you sent 2 messages in a row, and the websocket event comes back after the 2nd message is received, then one message will be displayed twice.

I think we have no choice to deduplicate on the whole list of messages, or maybe we could keep a store of messages already displayed (like a javascript Map() )  ?

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Nice PR, thanks for this ! 

I spotted a few issues with your implementation, let me know what you think about that :)

File: front/src/actions/message.js (hunk 1 above)
Comment (cicoub13) [reply front/src/actions/message.js]: Like it was really an UUID (v4), I found more meanfull `uuid` than `id`. But it's fixed

File: server/api/controllers/message.controller.js (hunk 2 above)
Comment (cicoub13) [reply server/api/controllers/message.controller.js]: It's just used to communicate via websocket. No need to persist it. Fixed

File: front/src/actions/message.js (hunk 3 above)
Comment (cicoub13) [reply front/src/actions/message.js]: Fixed by using filter on all messages.

**Review by atrovato — CHANGES_REQUESTED** [review]
Easy, nice, but do we want to add code in controllers?
Maybe we need to move the WebSocket event emit somewhere else, in the MessageHandler?
And add test on event content?

File: server/api/controllers/message.controller.js [hunk 4]
```diff
@@ -27,6 +27,13 @@ module.exports = function MessageController(gladys) {
       created_at: req.body.created_at || new Date(),
     };
     gladys.event.emit(EVENTS.MESSAGE.NEW, messageToSend);
+    // We emit message.sent to synchronize all discussions tabs in Front
+    messageToSend.id = req.body.id;
```
Comment (Pierre-Gilles) [inline server/api/controllers/message.controller.js]: Why do you edit the objet here? It'll affect the object sent previously as well (in JS, parameters are passed by reference when it's an object not by copy)

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]

**Comment by cicoub13** [comment]
> Easy, nice, but do we want to add code in controllers?
> Maybe we need to move the WebSocket event emit somewhere else, in the MessageHandler?

If we do this, the websocket event will be emitted with every process that send messages (including Telegram). Is it what we want ?

> And add test on event content?

Yes, I will add it 😉

File: server/api/controllers/message.controller.js (hunk 4 above)
Comment (cicoub13) [reply server/api/controllers/message.controller.js]: I need to create a copy object to add the id OR add the id only in the event ?

```
    gladys.event.emit(EVENTS.WEBSOCKET.SEND, {
      type: WEBSOCKET_MESSAGE_TYPES.MESSAGE.SENT,
      payload: messageToSend,
      userId: req.user.id,
      messageId: req.body.id, 
    });
```

**Comment by Pierre-Gilles** [comment]
> If we do this, the websocket event will be emitted with every process that send messages (including Telegram). Is it what we want ?

It is what we want indeed! 

When you are on Facebook web, if you send a message to a friend from your mobile, it appears on the web too :)

File: server/api/controllers/message.controller.js (hunk 4 above)
Comment (Pierre-Gilles) [reply server/api/controllers/message.controller.js]: I don't know, you added the id :p

**Comment by cicoub13** [comment]
I moved the code to the `handleMessage`. Like this, it works with Telegram.
And I added test 😄 

> When you are on Facebook web, if you send a message to a friend from your mobile, it appears on the web too :)

I agree but in our case, we will never be able to do :
- you write something in Chat in Gladys interface
- conversation is synchronized in live in Telegram

File: server/lib/message/message.handleEvent.js [hunk 5]
```diff
@@ -8,6 +9,13 @@ const logger = require('../../utils/logger');
  */
 async function handleEvent(message) {
   try {
+    console.log(message);
+    this.event.emit(EVENTS.WEBSOCKET.SEND, {
+      type: WEBSOCKET_MESSAGE_TYPES.MESSAGE.SENT,
+      payload: message,
+      userId: message.user.id,
+    });
+    delete message.id;
```
Comment (Pierre-Gilles) [inline server/lib/message/message.handleEvent.js]: again, why do you do this? you're mutating an object in live that was already sent previously. 

This will lead to weird behavior, because object are sent as references in JS.

File: server/lib/message/message.handleEvent.js [hunk 6]
```diff
@@ -8,6 +9,13 @@ const logger = require('../../utils/logger');
  */
 async function handleEvent(message) {
   try {
+    console.log(message);
```
Comment (Pierre-Gilles) [inline server/lib/message/message.handleEvent.js]: console.log should be removed

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
I still don't understand the flow with the id of the message. You create an id, then delete it, then another id is created in DB. All that on the same JS object. Why?

This implementation will lead to weird bugs!

File: server/lib/message/message.handleEvent.js (hunk 5 above)
Comment (cicoub13) [reply server/lib/message/message.handleEvent.js]: After forum discussion, behavior has changed. This discussion is outdated.

File: server/lib/message/message.handleEvent.js (hunk 6 above)
Comment (cicoub13) [reply server/lib/message/message.handleEvent.js]: Fixed

**Comment by cicoub13** [comment]
After forum discussion, behavior has changed. ID is generated in frontend and share during all the conversation.
I've made a small fix on Telegram to have the same `created_at` field in the front to be able to sort messages.

File: front/src/actions/message.js [hunk 7]
```diff
@@ -43,13 +43,18 @@ function createActions(store) {
       });
     },
     pushMessage(state, message) {
+      let newMessages = store.getState().messages;
+      // Check if message is already in the list
+      if (message.id && newMessages.filter(m => m.id === message.id).length) {
```
Comment (Pierre-Gilles) [inline front/src/actions/message.js]: .filter will scan the whole array of message, it could be long just to verify that the message is absent! 

I recommend using .find() instead (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/find). This function is optimized and will stop when the result was found

File: front/src/actions/message.js [hunk 8]
```diff
@@ -74,15 +79,16 @@ function createActions(store) {
...
-          created_at: new Date()
+          created_at: new Date(),
+          id
         };
-        const tempId = uuid.v4();
         // we first push the message
         const newState = update(state, {
           messages: {
-            $push: [Object.assign({}, newMessage, { tempId })]
+            $push: [Object.assign({}, newMessage, { id })]
```
Comment (Pierre-Gilles) [inline front/src/actions/message.js]: why do you do that? the id is already in newMessage

File: front/src/actions/message.js [hunk 9]
```diff
@@ -96,7 +102,7 @@ function createActions(store) {
         actions.scrollToBottom();
         // then we send the message
         const createdMessage = await state.httpClient.post('/api/v1/message', newMessage);
-        const messagesWithoutTempMessage = store.getState().messages.filter(message => message.tempId !== tempId);
+        const messagesWithoutTempMessage = store.getState().messages.filter(message => message.id !== id);
```
Comment (Pierre-Gilles) [inline front/src/actions/message.js]: I'm not sure this is useful anymore, now that the ID is generated client-side? what's the purpose here?

File: server/services/telegram/lib/message.new.js [hunk 10]
```diff
@@ -30,7 +30,7 @@ async function newMessage(msg) {
     user_id: user.id,
     user,
     language: user.language,
-    date: msg.date,
+    created_at: new Date(msg.date * 1000).toISOString(),
     text: msg.text,
```
Comment (Pierre-Gilles) [inline server/services/telegram/lib/message.new.js:35]: Now you require the `message.create`  function to have an `id`, but here there is no id passed. 

It can be ok, but it should be clear. Where is the id generated now? does it work? (I guess yes, and the id is generated by sequelize, but the code is not that clear on that point)

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Hi! I have a few feedbacks :)

File: server/services/telegram/lib/message.new.js (hunk 10 above)
Comment (cicoub13) [reply server/services/telegram/lib/message.new.js:35]: I generated one UUIDv4, more clear in code.

File: front/src/actions/message.js (hunk 9 above)
Comment (cicoub13) [reply front/src/actions/message.js]: Deleted

File: front/src/actions/message.js (hunk 8 above)
Comment (cicoub13) [reply front/src/actions/message.js]: Deleted

File: front/src/actions/message.js (hunk 7 above)
Comment (cicoub13) [reply front/src/actions/message.js]: Modified to use find()

File: server/services/telegram/lib/message.new.js [hunk 11]
```diff
@@ -30,8 +31,10 @@ async function newMessage(msg) {
...
+    // We generate ID as uuidv4 as Telegram doesn't give this type of ID
+    id: uuid.v4(),
```
Comment (atrovato) [inline server/services/telegram/lib/message.new.js:37]: Do we really an UUID v4 ID, telegram provides a message_id, which is an integer: https://core.telegram.org/bots/api#message

Comment (cicoub13) [reply server/services/telegram/lib/message.new.js:37]: We cannot mix UUIDv4 and int in Database
https://github.com/GladysAssistant/Gladys/blob/master/server/models/message.js#L6

Comment (atrovato) [reply server/services/telegram/lib/message.new.js:37]: So we store telegram messages in database? We don't delegate it to telegram?

Comment (cicoub13) [reply server/services/telegram/lib/message.new.js:37]: Exactly. We saved a copy (of user and gladys messages).

Comment (Pierre-Gilles) [reply server/services/telegram/lib/message.new.js:37]: yes we save them in the database

File: front/src/actions/message.js [hunk 12]
```diff
@@ -74,15 +90,16 @@ function createActions(store) {
...
-          created_at: new Date()
+          created_at: new Date(),
+          id
         };
-        const tempId = uuid.v4();
         // we first push the message
         const newState = update(state, {
           messages: {
-            $push: [Object.assign({}, newMessage, { tempId })]
+            $push: [Object.assign({}, newMessage)]
```
Comment (Pierre-Gilles) [inline front/src/actions/message.js]: Still, why do you do `Object.assign({}, newMessage)` ?

No need to create a new object here, as there is no longer a new attribute to add

File: front/src/actions/message.js [hunk 13]
```diff
@@ -93,15 +110,12 @@ function createActions(store) {
...
-        actions.scrollToBottom();
         // then we send the message
-        const createdMessage = await state.httpClient.post('/api/v1/message', newMessage);
-        const messagesWithoutTempMessage = store.getState().messages.filter(message => message.tempId !== tempId);
-        messagesWithoutTempMessage.push(createdMessage);
+        await state.httpClient.post('/api/v1/message', newMessage);
         // then we remove the message loading
         const finalState = update(state, {
           messages: {
-            $set: sortMessages(messagesWithoutTempMessage)
```
Comment (Pierre-Gilles) [inline front/src/actions/message.js:104]: why did you remove the sort? 

The goal of the sort is to avoid the case when you ask something to Gladys, and the replies appears before the question.

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]

File: front/src/actions/message.js (hunk 12 above)
Comment (cicoub13) [reply front/src/actions/message.js]: Fixed

File: front/src/actions/message.js (hunk 13 above)
Comment (cicoub13) [reply front/src/actions/message.js:104]: Fixed

**Review by atrovato — APPROVED** [review]
Looks fine.

**Review by Pierre-Gilles — APPROVED** [review]
