### PR TITLE
Fix NaN device state

### LINKED ISSUE #1392: Zigbee2mqtt integration insert "NaN" values in device_feature_state table, it shouldn't be possible
- [ ] In Zigbee2mqtt integration, fix what could cause that
- [ ] In Gladys Core, it shouldn't be possible to accept NaN values
- [ ] Clean existing NaN values in a DB migration

https://community.gladysassistant.com/t/help-probleme-avec-lagregation/6630/39?u=pierre-gilles

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Avoid NaN on device state number value.

Fixes: https://github.com/GladysAssistant/Gladys/issues/1392

### CODE REVIEW

**Comment by atrovato** [comment]
Tested with values in DB, those are well removed on startup.

File: server/lib/device/device.saveState.js [hunk 1]
```diff
@@ -13,6 +14,10 @@ const { EVENTS, WEBSOCKET_MESSAGE_TYPES } = require('../../utils/constants');
  * }, 12);
  */
 async function saveState(deviceFeature, newValue) {
+  if (Number.isNaN(newValue)) {
```
Comment (Pierre-Gilles) [inline server/lib/device/device.saveState.js:17]: I hope that most integration are sending state as Number and not string

Because before, you could send: "12" and it would work, now "12" rejects (I agree that it's a good thing)

By checking the code: 

- [x] MQTT
- [x] Zigbee2mqtt
- [x] Bluetooth 
- [x] Philips Hue
- [ ] Tasmota? (Not sure about this one)
- [x] Xiaomi
- [x] ZWave

**Review by Pierre-Gilles — COMMENTED** [review]
Looks good to me! Just a comment on the Tasmota integration to be sure that we send a Number and not a string

File: server/lib/device/device.saveState.js (hunk 1 above)
Comment (atrovato) [reply server/lib/device/device.saveState.js:17]: `isNaN` function handles numbers as string.
https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/isNaN

According to code, Tasmota implemented features only use numbers, but those can can stringlified.

Comment (Pierre-Gilles) [reply server/lib/device/device.saveState.js:17]: Indeed, Number.isNaN only return true for "NaN" values, my bad!

**Comment by atrovato** [comment]
I think we have a random test
```
  1) gateway
       gateway.backup
         should backup gladys:
     SequelizeDatabaseError: SQLITE_ERROR: cannot start a transaction within a transaction
      at Query.formatError (node_modules/sequelize/lib/dialects/sqlite/query.js:415:16)
      at Query._handleQueryResponse (node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
      at Statement.afterExecute (node_modules/sequelize/lib/dialects/sqlite/query.js:246:27)
```

That's not the 1st I get it.

**Comment by Pierre-Gilles** [comment]
I often have this one too, but I can't understand which query could be running at the same time 🤷‍♂️

In SQLite you can't run two transactions at the same time (very annoying aha)
