### PR TITLE
Avoid errorneous service on startup

### LINKED ISSUE #900: Avoid errorneous service on startup
Linked to #898 

On Gladys startup, if any service failed to start, do not load it on next startup.
And add "service status" in integration page.

### PR DESCRIPTION
**Pull request by atrovato**
Fixes #900

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Allow to not load errorneous service on startup.

### CODE REVIEW

File: server/migrations/20200104194451-sonoff-to-tasmota.js [hunk 1]
```diff
@@ -1,87 +0,0 @@
-const Promise = require('bluebird');
```
Comment (Pierre-Gilles) [inline server/migrations/20200104194451-sonoff-to-tasmota.js:1]: Why did you delete this migration?

Comment (atrovato) [reply server/migrations/20200104194451-sonoff-to-tasmota.js:1]: Because it uses service model which changes. It was not olny based on SQL but on code too.
This migration is supposed to change all 'sonoff' devices to tasmota (external id, service id).
But I don't thik this is really useful.
